/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import ActivitiesDataLayer.entities.Activities;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arkios
 */
public class Client_Main extends javax.swing.JFrame {
    
    LinkedList<Activities> actList;
    InetSocketAddress addr;
    
    /**
     * Creates new form Client_Main
     * @param parent
     * @param modal
     * @param sock
     */
    public Client_Main(InetSocketAddress ad, LinkedList<Activities> act) {
        initComponents();
        
        actList = act;
        addr = ad;
        initActivitiesTable();
    }
    
    private void initActivitiesTable(){
        DefaultTableModel model = (DefaultTableModel) ActivitiesTable.getModel();
        
        for(Activities act : actList){
            model.addRow(act.toVector());
        }
        
        ActivitiesTable.setModel(model);
    }
    
    
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ActivitiesTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        Quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ActivitiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Activitée", "Limite Participant", "Nombre Participant", "Date de début", "Duree Activitée", "Prix (HTVA)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ActivitiesTable.getTableHeader().setReorderingAllowed(false);
        ActivitiesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActivitiesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ActivitiesTable);
        ActivitiesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        menu_File.setText("File");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        menu_File.add(Logout);

        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        menu_File.add(Quitter);

        jMenuBar1.add(menu_File);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Client_Login log = new Client_Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ActivitiesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivitiesTableMouseClicked

        if (evt.getClickCount() == 2) {
            Activities act = actList.get(ActivitiesTable.getSelectedRow());
            
            System.out.println("Selectionné: " + act);
            Client_Activities window = null;
            try {
                window = new Client_Activities(this, true, addr, act);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Client_Main.class.getName()).log(Level.SEVERE, null, ex);
                System.exit(102);
            }
            window.setVisible(true);
        }
    }//GEN-LAST:event_ActivitiesTableMouseClicked

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_QuitterActionPerformed
    
    @Override
    public void dispose(){
        System.exit(0);
        super.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActivitiesTable;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem Quitter;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_File;
    // End of variables declaration//GEN-END:variables
}
