/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import db_access_tools.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 *
 * @author student
 */
public class Main extends javax.swing.JFrame {
    private static Connection connection = null;
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        Select_From_Combo.setSelectedIndex(0);
        Update_Update_Combo.setSelectedIndex(1);
        DeleteFrom_Combo.setSelectedIndex(0);
        Main.connection = ConnectionUtils.getMyConnection("MySQL");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        SelectPanel = new javax.swing.JPanel();
        Execute_Select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Select_From_Combo = new javax.swing.JComboBox<>();
        Select_Select_TextField = new javax.swing.JTextField();
        Select_Where_TextField = new javax.swing.JTextField();
        UpdatePanel = new javax.swing.JPanel();
        Execute_Update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Update_Set_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Update_Update_Combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Update_Where_TextField = new javax.swing.JTextField();
        DeletePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DeleteFrom_Combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Delete_Where_TextField = new javax.swing.JTextField();
        Execute_Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        NumRow = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Connexion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application Principale");

        SelectPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Execute_Select.setText("Execute");
        Execute_Select.setToolTipText("");
        Execute_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Execute_SelectActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT");

        jLabel2.setText("FROM");

        jLabel3.setText("WHERE");

        Select_From_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activites", "chambres", "complexes", "reservations", "voyageurs" }));

        Select_Select_TextField.setText("*");

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Select_From_Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Select_Select_TextField)
                            .addComponent(Select_Where_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Execute_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Select_Select_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Select_From_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Select_Where_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(Execute_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Select", SelectPanel);

        UpdatePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Execute_Update.setText("Execute");
        Execute_Update.setToolTipText("");
        Execute_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Execute_UpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("UPDATE");

        Update_Set_TextField.setText("nombreLits = 3");

        jLabel5.setText("SET");

        Update_Update_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activites", "chambres", "complexes", "reservations", "voyageurs" }));

        jLabel6.setText("WHERE");

        Update_Where_TextField.setText("numChambre = 1 AND idComplexe = 3");

        javax.swing.GroupLayout UpdatePanelLayout = new javax.swing.GroupLayout(UpdatePanel);
        UpdatePanel.setLayout(UpdatePanelLayout);
        UpdatePanelLayout.setHorizontalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Update_Set_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Update_Combo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_Where_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(UpdatePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Execute_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdatePanelLayout.setVerticalGroup(
            UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Update_Update_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_Set_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_Where_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(Execute_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update", UpdatePanel);

        DeletePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("DELETE FROM");

        DeleteFrom_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activites", "chambres", "complexes", "reservations", "voyageurs" }));

        jLabel8.setText("WHERE");

        Execute_Delete.setText("Execute");
        Execute_Delete.setToolTipText("");
        Execute_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Execute_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePanelLayout = new javax.swing.GroupLayout(DeletePanel);
        DeletePanel.setLayout(DeletePanelLayout);
        DeletePanelLayout.setHorizontalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DeletePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteFrom_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DeletePanelLayout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Delete_Where_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(DeletePanelLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(Execute_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        DeletePanelLayout.setVerticalGroup(
            DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DeleteFrom_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Where_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Execute_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Delete", DeletePanel);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable);

        jLabel9.setText("Row Number:");

        NumRow.setText("0");

        Menu_Connexion.setText("Connexion");
        Menu_Connexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu_ConnexionMousePressed(evt);
            }
        });
        jMenuBar1.add(Menu_Connexion);

        jMenu1.setText("Autres");

        jMenuItem1.setText("Recherche Voyageur Inscrit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(29, 29, 29)
                        .addComponent(NumRow)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(NumRow)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Execute_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Execute_SelectActionPerformed
        if(connection == null){
            JOptionPane.showMessageDialog(null, "Erreur Aucunne connexion a la BDD", "Erreur Aucunne connexion a la BDD", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        String Select = Select_Select_TextField.getText();
        String From = (String) Select_From_Combo.getSelectedItem();
        String Where = Select_Where_TextField.getText();
        
        if(Select.equals("") || From == null){
            JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas rempli tout les champs...", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(Where.equals("")){ Where = "1=1";}
        
        TableModel t = ConnectionUtils.select(connection, Select, From, Where);
        this.jTable.setModel(t); 
        
        //int tmp = ConnectionUtils.NumRow(connection, From, Where);
        //this.NumRow.setText(Integer.toString(tmp));
    }//GEN-LAST:event_Execute_SelectActionPerformed

    private void Execute_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Execute_UpdateActionPerformed
        if(connection == null){
            JOptionPane.showMessageDialog(null, "Erreur Aucunne connexion a la BDD", "Erreur Aucunne connexion a la BDD", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String Set = Update_Set_TextField.getText();
        String Update = (String) Update_Update_Combo.getSelectedItem();
        String Where = Update_Where_TextField.getText();
        
        if(Set.equals("") || Update == null || Where.equals("")){
            JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas rempli tout les champs...", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        TableModel t = ConnectionUtils.update(connection, Update, Set, Where);
        this.jTable.setModel(t);  
        
        int tmp = ConnectionUtils.NumRow(connection, Update, Where);
        this.NumRow.setText(Integer.toString(tmp));
    }//GEN-LAST:event_Execute_UpdateActionPerformed

    private void Execute_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Execute_DeleteActionPerformed
        if(connection == null){
            JOptionPane.showMessageDialog(null, "Erreur Aucunne connexion a la BDD", "Erreur Aucunne connexion a la BDD", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String DeleteFrom = (String) DeleteFrom_Combo.getSelectedItem();
        String Where = Delete_Where_TextField.getText();
        
        if(DeleteFrom == null || Where.equals("")){
            JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas rempli tout les champs...", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        TableModel t = ConnectionUtils.delete(connection, DeleteFrom, Where);
        this.jTable.setModel(t);  
        
        int tmp = ConnectionUtils.NumRow(connection, DeleteFrom, Where);
        this.NumRow.setText(Integer.toString(tmp));
    }//GEN-LAST:event_Execute_DeleteActionPerformed

    private void Menu_ConnexionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ConnexionMousePressed
        Object[] choix = { "MySQL","Oracle", "Disconnect" };
        JComboBox comboBox = new JComboBox(choix);
        comboBox.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(null, comboBox, "Choisissez le type de Base de Donnée", JOptionPane.QUESTION_MESSAGE);
        
        String name = (String) comboBox.getSelectedItem();
        
        Main.connection = ConnectionUtils.getMyConnection(name);
    }//GEN-LAST:event_Menu_ConnexionMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        voyageurinscrit v = new voyageurinscrit(connection);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DeleteFrom_Combo;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JTextField Delete_Where_TextField;
    private javax.swing.JButton Execute_Delete;
    private javax.swing.JButton Execute_Select;
    private javax.swing.JButton Execute_Update;
    private javax.swing.JMenu Menu_Connexion;
    private javax.swing.JLabel NumRow;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JComboBox<String> Select_From_Combo;
    private javax.swing.JTextField Select_Select_TextField;
    private javax.swing.JTextField Select_Where_TextField;
    private javax.swing.JPanel UpdatePanel;
    private javax.swing.JTextField Update_Set_TextField;
    private javax.swing.JComboBox<String> Update_Update_Combo;
    private javax.swing.JTextField Update_Where_TextField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
