/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ProtocolROMP.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.ConnectException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.LinkedList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Thomas
 */
public class login extends javax.swing.JFrame {
    private Socket sock;
    private final Properties config;
    private InetSocketAddress Addr;
    
    /**
     * Creates new form Client_Activities
     * @throws java.io.IOException
     */
    public login() throws IOException {
        sock = new Socket();
        //sock.setSoTimeout(5000);
        initComponents();
        
        File f = new File("client.cfg");
        config = new Properties();

        if (f.createNewFile()) {
            OutputStream os = new FileOutputStream(f.getPath());
            config.setProperty("port", "50006");
            config.setProperty("ip", "127.0.0.1");

            config.store(os, "Configuration du Client:");
        } else {
            FileInputStream fis = new FileInputStream(f.getPath());
            config.load(fis);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Login = new javax.swing.JButton();
        KO = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Login.setText("Connexion");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    LoginActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        KO.setText("Annuler");
        KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    KOActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        password.setText("abc");

        email.setText("thomas.bastin@inpres.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(Login))
                    .addComponent(email))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KO)
                    .addComponent(Login))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    private void KOActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                   
        sock.close();
        System.exit(0);
    }                                  

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        try {
            InitSock();
        } catch(SocketException ex){
            JOptionPane.showMessageDialog(this, "Impossible de se connecter au serveur:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Impossible to connect to the server");
            return;
        }
        
        catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        
        String login = email.getText();
        String hash = "";
        
        //Hashage Password
        try {
            hash = hashMD5(password.getPassword());
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(0);
        }
        
                
        //Try Login
        try {
            
            sock.connect(Addr);
            ObjectOutputStream oos = new ObjectOutputStream(sock.getOutputStream());
            System.out.println("Envoie d'un Objet LoginRequest");
            //Send Login request 
            oos.writeObject(new LoginRequest(login, hash));
            
            ObjectInputStream ios = new ObjectInputStream(sock.getInputStream());
            System.out.println("Récupération des Input Stream");
            Object resp = ios.readObject();
            
            //If it's a Login you look respond, else look if it's a timeout
            LoginResponse lr;
            TimeOut to;
            
            
            if(resp instanceof LoginResponse){
                lr = (LoginResponse) resp;
            } else if(resp instanceof TimeOut){
                to = (TimeOut) resp;
                JOptionPane.showMessageDialog(this, "Le Serveur c'est éteint", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else{
                JOptionPane.showMessageDialog(this, "Message reçus du Serveur Inconnus", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //check login response:
            switch(lr.getCode()){
                case 200:
                        Construct_MainPage();
                    break;
                    
                case 401:
                        JOptionPane.showMessageDialog(this, "L'adresse email est invalide", "Erreur", JOptionPane.ERROR_MESSAGE);
                    break;
                    
                case 402:
                        JOptionPane.showMessageDialog(this, "Mauvais mot de passe", "Erreur", JOptionPane.ERROR_MESSAGE);
                    break;
                    
                case 403:
                        JOptionPane.showMessageDialog(this, "Erreur Base de Donnée: " + lr.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                    break;
                    
                case 404:                   
                default:
                    JOptionPane.showMessageDialog(this, "Erreur Inconnue", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
                    
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "La connexion n'a pas réussie\n" + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        sock.close();
    }                                     
    
    
   
    private void Construct_MainPage() throws IOException, ClassNotFoundException{

        System.out.println("LoginRéussi, construction de la fenètre main.");
        MainApp window = new MainApp(sock,Addr);
        this.setVisible(false);
        window.setVisible(true);
        this.dispose();
    }
    
    private void InitSock() throws IOException, SocketException{        
        InetAddress ip;
        int port;
        
        //Get Port & IP
        try{
            port = Integer.parseInt(config.getProperty("port"));
            ip = InetAddress.getByName((String)config.getProperty("ip"));
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Le Port ne suit pas un format valide (Client.cfg)", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this, "L'ip ne suit pas un format valide (Client.cfg)", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(sock.isClosed() || !sock.isConnected()) {sock = new Socket();}
        Addr = new InetSocketAddress(ip,port);
        System.out.println("Socket Lancer");
    }
    
    
    //Small Utility fct to convert a char[] to a String Digest
    private String hashMD5(char[] pswd) throws NoSuchAlgorithmException, UnsupportedEncodingException{
        byte[] qzdqzd = new String(pswd).getBytes("UTF-8");
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(qzdqzd);
        
        return DatatypeConverter.printHexBinary(md.digest()).toUpperCase();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new login().setVisible(true); 
            } catch (IOException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton KO;
    private javax.swing.JButton Login;
    private javax.swing.JTextField email;
    private javax.swing.JPasswordField password;
    // End of variables declaration                   
}
